= OneToMany BIDIREZIONALE
// :icons: font
// :leveloffset: +1

Il modo migliore per mappare un'associazione @OneToMany è fare affidamento sul @ManyToOne lato per propagare tutte le modifiche allo stato dell'entità:

[,java]
----
@Entity
@NoArgsConstructor
@Getter
@Setter
public class PersonaBi {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  private String name;

  @OneToMany(mappedBy = "proprietario", cascade = CascadeType.ALL, orphanRemoval = true)
  private List<MacchinaBi> macchine = new ArrayList<>();

  /**
   * presenta due metodi di utilità (ad esempio aggiungiMacchina e rimuoviMacchina) che vengono utilizzati
   * per sincronizzare entrambi i lati dell'associazione bidirezionale. Dovresti sempre fornire
   * questi metodi ogni volta che lavori con un'associazione bidirezionale poiché, altrimenti,
   * rischi di problemi di propagazione dello stato molto sottili
   */
  public void aggiungiMacchina(MacchinaBi macchinaBi) {
    macchine.add(macchinaBi);
    macchinaBi.setProprietario(this);
  }

  public void rimuoviMacchina(MacchinaBi macchinaBi) {
    macchine.remove(macchinaBi);
    macchinaBi.setProprietario(null);
  }
}
----

[IMPORTANT]
====
.Classe Persona
presenta due metodi di utilità (ad esempio aggiungiMacchina e rimuoviMacchina) che vengono utilizzati per sincronizzare entrambi i lati dell'associazione bidirezionale.
Dovresti sempre fornire questi metodi ogni volta che lavori con un'associazione bidirezionale poiché, altrimenti, rischi di problemi di propagazione dello stato molto sottili
====

[,java]
----
@Entity
@NoArgsConstructor
@Getter
@Setter
public class MacchinaBi {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;

  private String modello;

  /**
   * L' @ManyToOneassociazione utilizza FetchType.LAZYperché, altrimenti, ricadremmo sul recupero
   * EAGER, il che è negativo per le prestazioni .
   */
  @ManyToOne(fetch = FetchType.LAZY)
  private PersonaBi proprietario;

  /**
   * L'entità figlio, Macchina, implementa i metodi equalse hashCode. Poiché non possiamo fare
   * affidamento su un identificatore naturale per i controlli di uguaglianza , dobbiamo utilizzare
   * invece l'identificatore di entità per il equalsmetodo. Tuttavia, è necessario farlo
   * correttamente in modo che l'uguaglianza sia coerente in tutte le transizioni dello stato
   * dell'entità , che è anche il motivo per cui hashCodedeve essere un valore costante. Poiché
   * facciamo affidamento sull'uguaglianza per removeComment, è buona norma sovrascrivere equalse
   * hashCodeper l'entità figlio in un'associazione bidirezionale.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    MacchinaBi macchina = (MacchinaBi) o;
    return Objects.equals(id, macchina.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id);
  }
}
----

° inizializzazione dei dati con una persona che possiede due macchine

[,sql]
----
insert into persona_bi (name,id) values (?,default)
insert into macchina_bi (modello,proprietario_id,id) values (?,?,default)
insert into macchina_bi (modello,proprietario_id,id) values (?,?,default)
----

° Rimozione della macchina da lato Persona:

[,sql]
----
select p1_0.id,p1_0.name from persona_bi p1_0
select m1_0.proprietario_id,m1_0.id,m1_0.modello from macchina_bi m1_0 where m1_0.proprietario_id=?
update macchina_bi set modello=?,proprietario_id=? where id=?
----

° Rimozione Del propietaro dalla macchina:

[,sql]
----
select m1_0.id,m1_0.modello,m1_0.proprietario_id from macchina_bi m1_0 where m1_0.proprietario_id is not null
update macchina_bi set modello=?,proprietario_id=? where id=?
----

° Rimozione Del propietaro dalla macchina, utilizzando anche il metodo del proprietario di rimuovere la macchina:

[,java]
----
public void rimuoviProprietario(){
    // this = è la macchina.
    //TODO verificare se è necessario rimuovere dal proprietario la macchina???
    this.proprietario.rimuoviMacchina(this);
    this.setProprietario(null);
  }
----

.. Devo ancora capire se sia necessario per tenere sincronizzati i dati lato java (forse dipende dal caso d'uso).

[,sql]
----
select m1_0.id,m1_0.modello,m1_0.proprietario_id from macchina_bi m1_0 where m1_0.proprietario_id is not null
select p1_0.id,p1_0.name from persona_bi p1_0 where p1_0.id=?
select m1_0.proprietario_id,m1_0.id,m1_0.modello from macchina_bi m1_0 where m1_0.proprietario_id=?
update macchina_bi set modello=?,proprietario_id=? where id=?
----

// :leveloffset: -1